name: Matrix with Reusable Workflow

on: [push]

jobs:
  example-matrix-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ["production", "staging", "development"]
    steps:
      - name: Call Reusable Workflow
        uses: ./.github/workflows/common-task.yml@main
        with:
          environment: ${{ matrix.environment }}
