name: Matrix with Reusable Workflow

on: [push]

jobs:
  # run after reusable workflow
  test-job2:
    runs-on: ubuntu-latest
    steps:
      - name: Echo environment in matrix
        run: echo "Running common task in ${{ inputs.environment }} environment"
      - run: touch file2.txt
      - name: display file list
        run: ls -l
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  call-reusable-workflow:
    uses: ./.github/workflows/common-task.yml
    with:
      environment: ${{ matrix.environment }}
    strategy:
      fail-fast: false
      matrix:
        environment: ["production", "staging", "development"]
