name: Matrix with Reusable Workflow

on: [push]

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/common-task.yml
    with:
      environment: ${{ matrix.environment }}
    strategy:
      fail-fast: false
      matrix:
        environment: ["production", "staging", "development"]
