name: Matrix with Reusable Workflow

on: [push]

jobs:
  example-matrix-job:
    uses: ./.github/workflows/common-task.yml@main
    with:
      environment: ${{ matrix.environment }}
    strategy:
      matrix:
        environment: ['production', 'staging', 'development']
