name: mysql-agent version upgrade
run-name: Deploy to ${{ inputs.env }} mysql-agent ${{inputs.mysql-agent-version}} server-agent ${{inputs.server-agent-version}} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: 'deployment env'
        required: true
        options:
          - mysql-master-dev
          - mysql-stage-dev
          - mysql-stage-prod
          - mysql-real-dev
          - mysql-real-prod
          - mysql-real-prod-sgp
      mysql-agent-version:
        type: string
        description: "mysql-agent version (ex: v0.1.55) | empty = run only server-agent upgrade"
      server-agent-version:
        type: string
        description: "server-agent version (ex: v0.0.30) | empty = run only mysql-agent upgrade"
      namespace:
        type: string
        description: 'target namespace - valid value: verda-vcsmt | ["dev", "qa", "prod"]'
      cluster:
        type: string
        description: "target cluster name with single namespace - empty = all clusters in namespace"
      forks:
        type: string
        description: "ansible parallel execution. default: 5"
jobs:
  generate-namespaces:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.dataStep.outputs.myoutput }}
    steps:
      - id: dataStep
        run: |
          NAMESPACES=$(jq -nR '[range(200) | "namespace-\(.)"]' | jq -r @json)
          echo "myoutput=$(jq -cn --argjson namespaces "$NAMESPACES" '{namespaces: $namespaces}')" >> $GITHUB_OUTPUT
        shell: bash
  upgrade-agent:
    name: ${{ matrix.namespaces }}
    needs: generate-namespaces
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix: ${{fromJson(needs.generate-namespaces.outputs.matrix)}}
    steps:
      - run: echo "Using namespace ${{ matrix.namespaces }}"
