name: mysql-agent version upgrade
run-name: Deploy to ${{ inputs.env }} mysql-agent ${{inputs.mysql-agent-version}} server-agent ${{inputs.server-agent-version}} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: 'deployment env'
        required: true
        options:
          - mysql-master-dev
          - mysql-stage-dev
          - mysql-stage-prod
          - mysql-real-dev
          - mysql-real-prod
          - mysql-real-prod-sgp
      mysql-agent-version:
        type: string
        description: "mysql-agent version (ex: v0.1.55) | empty = run only server-agent upgrade"
      server-agent-version:
        type: string
        description: "server-agent version (ex: v0.0.30) | empty = run only mysql-agent upgrade"
      namespace:
        type: string
        description: 'target namespace - valid value: verda-vcsmt | ["dev", "qa", "prod"]'
      cluster:
        type: string
        description: "target cluster name with single namespace - empty = all clusters in namespace"
      forks:
        type: string
        description: "ansible parallel execution. default: 5"
jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          echo "::set-output name=matrix::$(jq -nR '[range(100) | "namespace-\(.)"]' | jq -r @json)"
        shell: bash

  use-matrix:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    steps:
      - run: echo "Using namespace ${{ matrix }}"
